final_project/final_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('url_shortener.urls')),
    path('admin/', admin.site.urls),
]

final_project/url_shortener/urls.py
from django.urls import path
from . import views

app_name = 'url_shortener'

urlpatterns = [
    path('', views.index, name='index'),  # url for home page
    path('u/<str:short_url>', views.handle_short_url, name='handle'), # url for handling short urls from users
    path('allLinks', views.AllLinksView.as_view(), name='all_links'), # url for all links page
    path('myurl', views.create_short_url, name='create'), # url for creating new short urls
    path('delete/<int:short_url_id>', views.delete_short_url, name='delete'), # url for deleting short urls
]

final_project/url_shortener/models.py
from django.db import models

# Create your models here.


class ShortURL(models.Model):
    """
    A class to represent a model of short url.

    Attributes
    ----------
    hashed_url : str,
        hash-salted full original link
    full_url : str,
        full original link
    number_of_uses : unsigned int,
        number of uses of the short link by the user

    """
    hashed_url = models.CharField(max_length=8, unique=True)
    full_url = models.URLField(unique=True)
    number_of_uses = models.PositiveIntegerField()

final_project/url_shortener/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.http import HttpResponse, HttpResponseRedirect, HttpRequest
from django.views import generic
from django.urls import reverse
from . import utils
from .models import ShortURL
from django.db.models import F

# Create your views here.


# view for rendering home page
def index(request):
    return render(request=request, template_name='url_shortener/index.html')


class AllLinksView(generic.ListView):
    model = ShortURL
    template_name = 'url_shortener/all_links.html'
    context_object_name = 'short_urls'

    # return short url objects ordering them by number_of_uses
    def get_queryset(self):
        return ShortURL.objects.order_by('-number_of_uses')


# view for creating new short urls
def create_short_url(request):

    # get input full url from user's request
    full_url = request.POST['input-url']
    
    # check if user input has url format
    if utils.is_valid_url(full_url):

        # try to get a short_url model that already exists
        try:
            # trying to get model of short_url from db with input full_url
            short_url_model = ShortURL.objects.get(full_url=full_url)

            # form short url for user on template
            short_url = utils.form_short_url(request, short_url_model.hashed_url)

            # return render of index page with short url that already exists
            return render(request=request, template_name='url_shortener/index.html', 
                context={'short_url': short_url, 'href_short_url' : "http://" + short_url})

        # except that a model of short url does not exist
        except ShortURL.DoesNotExist:

            # create hash with salt of full url
            hash_url = utils.hash_url(full_url)

            # add new record to database
            ShortURL.objects.create(hashed_url=hash_url, full_url=full_url, number_of_uses=0)

            # form short url for user on template
            short_url = utils.form_short_url(request, hash_url)

            # return render of index page with short url
            return render(request=request, template_name='url_shortener/index.html', 
                context={'short_url': short_url, 'href_short_url' : "http://" + short_url})

    else:

        # form error message for user
        error_message = 'Input full URL`s format is wrong. Please try again...'

        # return render of index page with error_message
        return render(request=request, template_name='url_shortener/index.html', 
            context={'error_message': error_message})


# view for short url request handling, return full source url
def handle_short_url(request, short_url):
    
    # get object from db with short url
    short_url_model = get_object_or_404(klass=ShortURL, hashed_url=short_url)

    # increase the number of uses of this short url by 1
    short_url_model.number_of_uses = F('number_of_uses') + 1

    # save changes in db
    short_url_model.save()

    # get full url of short url model from db
    full_url = short_url_model.full_url

    # return redirect of user to full source url
    return redirect(full_url)


# view for deleting short urls
def delete_short_url(request, short_url_id):

    # find short url model in db by pk
    short_url_model = get_object_or_404(klass=ShortURL, pk=short_url_id)

    # delete record from db
    short_url_model.delete()

    # return redirect to all links page without deleted record
    return redirect('url_shortener:all_links')

final_project/url_shortener/templates/url_shortener/all_links.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'url_shortener/bootstrap.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'url_shortener/style.css' %}">

<div name="all_links-center" >
    <h1><strong>All Links</strong></h1>

    <a href="{% url 'url_shortener:index' %}" class="badge badge-primary" name="all_links">Home</a>


    {% if short_urls %}
        <table class="table table-striped table-responsive-md btn-table">

            <thead>
                <tr>
                    <th>Number of uses</th>
                    <th>Short URL</th>
                    <th>Full URL</th>
                </tr>
                
            </thead>
            
            <tbody>
                {% for short_url in short_urls %}
                <form action="{% url 'url_shortener:delete' short_url.id %}" method="delete">
                    <tr>
                        <th class="center" scope="row">{{ short_url.number_of_uses }}</th>

                        <td name="short_url_row">
                            <a href="u/{{ short_url.hashed_url }}">{{ short_url.hashed_url }}</a>
                            &nbsp;
                            &nbsp;
                            &nbsp;
                            <input name="delete-shorturl" type="submit" class="btn btn-danger" value="Delete">
                        </td>

                        <td>
                            <a href="{{ short_url.full_url }}" name="all_links">
                                {{ short_url.full_url }}
                            </a>

                        </td>

                    </tr>
                </form>

                {% endfor %}

            </tbody>

        </table>

    {% else %}

        <h3><strong>No short urls available</strong></h3>

    {% endif %}

</div>

final_project/url_shortener/templates/url_shortener/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'url_shortener/bootstrap.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'url_shortener/style.css' %}">

<form action="{% url 'url_shortener:create' %}" method="post">
    {% csrf_token %}
    <div name="index-center">
        <h1><strong>URL Shortener</strong></h1>

        <a href="{% url 'url_shortener:all_links' %}" class="badge badge-primary" name="all_links">All Links</a>

        <div class="input-group mb-3">

            <input name="input-url" type="url" class="form-control" placeholder="Enter a long URL to make a ShortURL" 
                aria-label="Enter a long URL to make a ShortURL" aria-describedby="basic-addon2" required>

            <div class="input-group-append">
                {% if not short_url %} 
                        <input name="submit-url" class="btn btn-primary" type="submit" value="Make ShortURL!">

                {% else %} 
                        <a href="{% url 'url_shortener:index' %}"
                           name="shorten-another-url" class="btn btn-primary">
                           Shorten another
                        </a>
                {% endif %}
            </div>
        </div>

        {% if short_url %} 
            <div class="alert alert-success" role="alert">
                <a href="{{ href_short_url }}"
                    name="short-url">
                    {{ short_url }}
                </a>
            </div>
        {% endif %}

        {% if error_message %} 
            <div class="alert alert-danger" role="alert">
                {{ error_message }}
            </div>
        {% endif %}
    <div>
</form>